### ISSUE TITLE
enhancement: setup native parameters for driver

### ISSUE THREAD

**Issue by Oskang09** [si3nloong/goloquent#48]
# Issues

Due to some heavy usage of goroutine, it cause mysql driver to be failed via too many connections. There's a workaround by setting paramters to native mysql driver.

# Feature & Solving

Expose another function which process native driver some kind function like `func(*sql.DB) *sql.DB` . Currently workaround via screenshot below but break some features, so better to handle by library.

![image](https://user-images.githubusercontent.com/15674107/132311585-7cd884d5-c558-4d80-ba79-39062d3814d6.png)

Will send out a PR soon, for this changes.

**Comment by si3nloong** [comment]
I think exposing the native function will be good
